### ISSUE TITLE
Update stergere produs

### ISSUE THREAD

**Issue by CatalinIancu** [IujyrinoT2/Magazin-ASD#19]
Functie de stergere produs trebuie sa elibere codul produsului

**Comment by IujyrinoT2** [comment]
Nu o sa dau pull request pana nu face @radu-cristian-ivascu merge primul ca am niste dubii care trebuie testate.

**Comment by IujyrinoT2** [comment]
Am rezolvat functia de stergere dar am modificat si functia de adaugare produs #8 sa adauge elementele noi la final in loc sa le adauge la inceput
