### ISSUE TITLE
Validare date (pretul sa fie pozitiv, cantitatea sa fie pozitiva, pretul, cantitatea si codul sa fie numere si nu string)

### ISSUE THREAD

**Issue by CatalinIancu** [IujyrinoT2/Magazin-ASD#38]

**Comment by Az3m** [comment]
- [x] Validare nume produs in ImportStoc (Numele nu va avea voie sa aiba peste 255 de caractere)
- [x] Validare nume produs in AdaugaProdus (Numele nu va avea voie sa aiba peste 255 de caractere)
- [x] Validare stoc produs in ImportStoc (Nu are voie sa fie negativ si sa fie sub limita oferita de unsigned int)
- [x]  Validare stoc produs in AdaugaProdus (Nu are voie sa fie negativ si sa fie sub limita oferita de unsigned int)
- [x] Validare pret produs in ImportStoc (Nu are voie sa fie negativ si sa fie in limita oferita de float)
- [x] Validare pret produs in AdaugaProdu (Nu are voie sa fie negativ si sa fie in limita oferita de float)

**Comment by Az3m** [comment]
Done
