### ISSUE TITLE
Creare Produs* CautareProdus(int codProdus)

### ISSUE THREAD

**Issue by IujyrinoT2** [IujyrinoT2/Magazin-ASD#4]
Produs* CautareProdus(int codProdus){
    //Va gasi produsul cautat (dupa cod produs)
    //Va returna produsul.
}

**Comment by IujyrinoT2** [comment]
Poti te rog sa returnezi nullptr in caz ca nu s-a gasit produsul?

**Comment by Az3m** [comment]
il inchid pe asta deoarece le-am implementat pe ambele in #5
